<a href="https://colab.research.google.com/github/GuptaNavdeep1983/CS767/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import random
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import math
from sklearn import preprocessing
from sklearn.metrics import log_loss

In [99]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference
def relu(x):
  output = [0] * len(x)
  for index, item in enumerate(x): 
    output[index] = item if item > 0.0 else 0.0 
  return output

In [88]:
class Layer():
  def __init__(self, name, units, input_dim):
    self.name = name
    self.w = [[random.uniform(-2,2) for _ in range(input_dim)] for _ in range(units)]
    self.b = [0 for _ in range(units)]
    self.output = [bias for bias in self.b]
  def calculate_output(self, inputs, activation=sigmoid):
    self.output = [bias for bias in self.b]
    for row_index, col in enumerate(self.w):
      for col_index, weight in enumerate(col):
        self.output[row_index] += weight * inputs[row_index]
    self.output = activation(self.output)
    return self.output 
  def update_weights(expected_output, inputs):
    for row_index, col in enumerate(self.w):
      for col_index, weight in enumerate(col):
        error = self.output[row_index] - expected_output
        self.w[row_index][col_index] = self.w[row_index][col_index] + (error * inputs[row_index])
  def updated_output():
    

In [90]:
from pprint import pprint
layer1 = Layer("Hidden1", 3, 4)
layer2 = Layer("Output", 3, 4)

layers = [layer1, layer2]
pprint(vars(layer1))
pprint(vars(layer2))

{'b': [0, 0, 0],
 'name': 'Hidden1',
 'output': [0, 0, 0],
 'w': [[0.6140459213378167,
        1.7399374232390987,
        -1.294715532982241,
        1.6482569449220001],
       [1.841374243124395,
        0.6199576876564672,
        -0.5753909466090628,
        1.7836395890508445],
       [-1.9803039422291273,
        0.8399453984550393,
        0.5307812997567027,
        1.9957125405550808]]}
{'b': [0, 0, 0],
 'name': 'Output',
 'output': [0, 0, 0],
 'w': [[-0.7905731416947108,
        1.3422972215976565,
        -0.9933314901811352,
        -1.1826429521724235],
       [-1.2593110805814214,
        -1.3948104520615114,
        -1.1818415635510164,
        -1.4210833753073047],
       [1.0665465173631814,
        -1.4367320120747324,
        0.6044884402707349,
        -0.7405204386511519]]}


In [6]:
iris = load_iris()

iris_columns = ['sepal_len', 'sepal_width', 'petal_length', 'petal_width', 'target']
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris_columns)

In [117]:
from sklearn.model_selection import train_test_split
X = df[['sepal_len', 'sepal_width', 'petal_length', 'petal_width']]
y = df[['target']]
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2,
                                                    random_state = 10)


X_train.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [8]:
import random
random.seed(34)
selected_rows = random.sample(range(0,119),   5)

In [121]:
lb = preprocessing.LabelBinarizer()
lb.fit([0,1,2])
lb.transform([0])


array([[1, 0, 0]])

In [61]:
X_train.loc[selected_rows, :]

sepal_len  sepal_width  petal_length  petal_width
67         5.5          2.4           3.8          1.1
45         6.3          2.8           5.1          1.5
74         4.8          3.4           1.6          0.2
3          5.8          2.8           5.1          2.4
107        5.4          3.9           1.3          0.4

In [164]:
def categorical_cross_entropy(actual, predicted):
	sum_score = 0.0
	for i in range(len(actual)):
			sum_score += actual[i] * math.log(1e-15 + predicted[i])
	mean_sum_score = (1.0 / len(actual)) * sum_score
	return -mean_sum_score

1.0

In [165]:
def train_weights_using_mini_batch_gradient_descent(X_train, y_train, num_epochs, learning_rate, layers):
  # weights for all the features 
  index = 0;
  df_plot = []
  error = 0
  mini_batch = X_train.loc[selected_rows, :]
  y_train = y_train.loc[selected_rows, :]
  while index < num_epochs:
    for rowIndex, row in mini_batch.iterrows():
      print(y_train.loc[rowIndex,'target'])
      output = row
      for layer_idx, layer in enumerate(layers):
        if layer_idx == len(layers) - 1:
          output = layer.calculate_output(output, softmax)
        else:
          output = layer.calculate_output(output, relu)
      print(output)
      # print(lb.transform([y_train.loc[rowIndex,'target']]))
      print(categorical_cross_entropy(lb.transform([y_train.loc[rowIndex,'target']])[0], output))
      error += log_loss([y_train.loc[rowIndex,'target']], [output], labels=[0.0, 1.0, 2.0])
    average_error = error/mini_batch.shape[0]
    # for layer_idx, layer in enumerate(layers):
    #   layer.update_weights()
    index = index + 1
  # df_plot = pd.DataFrame(df_plot, columns=['mse', 'epoch'])
  return


print("Creating model using training data")
train_weights_using_mini_batch_gradient_descent(X_train, y_train, 1, 0.1, layers)

Creating model using training data
1.0
[4.50378481e-10 1.12383829e-19 1.00000000e+00]
11.512888005798846
2.0
[3.32522210e-11 1.24636912e-22 1.00000000e+00]
1.1083763536792906e-11
0.0
[2.08968348e-09 1.00516433e-28 9.99999998e-01]
6.6620842499556305
2.0
[2.99756535e-10 1.24636912e-22 1.00000000e+00]
9.9918480911571e-11
0.0
[1.20982181e-10 5.26980272e-33 1.00000000e+00]
7.611789860511054
